---
title: "Untitled"
author:
- name: Kieran Healy
  affiliation: Duke University
  email: kieran.healy@duke.edu
date: '`r format(Sys.Date(), "%B %d, %Y")`'
crossrefYaml: "config/pandoc-crossref-settings.yaml"
output:
  md_document: 
  html_document: distill::distill_article
  pdf_document: 
    md_extensions: +simple_tables+table_captions+yaml_metadata_block+smart
    template: /Users/kjhealy/.pandoc/templates/rmd-latex.template
    pandoc_args: [
      "--bibliography", "/Users/kjhealy/Documents/bibs/socbib-pandoc.bib",
      "--filter", "pandoc-crossref",
      "--citeproc",
      "--csl", "/Users/kjhealy/.pandoc/csl/ajps.csl"
      ]      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
                      fig.path='figures/',
                      cache.path='cache/',
                      dev=c("ragg_png","cairo_pdf"),
                      fig.asp = 0.7,
                      fig.retina = 2,
                      fig.show='hold',
                      fig.lp="fig:",
                      cache=FALSE,
                      par=TRUE,
                      echo=FALSE,
                      warning = FALSE,
                      results="asis",
                      message=FALSE)

knitr::knit_hooks$set(par = function(before, options, envir){
    if (before && options$fig.show != 'none') par(mar = c(4,4,.1,.1), cex.lab = .95, cex.axis = .9, mgp = c(2, .7, 0), tcl = -.3)
}, crop=knitr::hook_pdfcrop)

knitr::opts_knit$set(kfigr.prefix=TRUE,
              kfigr.link=FALSE)

```

```{r libraries}

library(tidyverse)
library(here)
library(janitor)
library(socviz)
library(ggrepel)

library(systemfonts)
clear_registry()

register_variant(
  name = "Myriad Pro SemiCondensed",
  family = "Myriad Pro",
  width = "semicondensed",
  weight = c("normal", "semibold"),
)

library(showtext)
showtext_opts(dpi = 300)
showtext_auto()

library(myriad)
import_myriad_semi()


theme_set(theme_myriad_semi())

```

# Header

```{r}

```


